### ISSUE TITLE
Fix the issues with font Awesome icons

### ISSUE THREAD

**Issue by sukeshrs** [sukeshrs/smart-chat-ui#13]
Some of the fa icons are not showing up properly . Most probably this is due to the version which is used .Upgrage to font awesome 5 to fix the issue

**Comment by sukeshrs** [comment]
URLS for reference 
https://stackoverflow.com/questions/48184079/include-fortawesome-fontawesome-to-angular-cli-project
https://fontawesome.com/how-to-use/use-with-node-js

**Comment by victoriaagb** [comment]
Fixed
